# Generated by Django 4.0.4 on 2022-04-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='photo',
            field=models.ImageField(default=None, upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='news',
            name='views',
            field=models.IntegerField(default=1, verbose_name='Просмотры'),
        ),
    ]
