# Generated by Django 4.0.4 on 2022-04-14 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storm', '0002_news_photo_alter_news_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='photo',
        ),
    ]
