# Generated by Django 4.0.4 on 2022-05-09 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storm', '0003_remove_news_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='views',
        ),
    ]
